name: Pipeline

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

permissions:
    contents: read
    pages: write
    id-token: write

jobs:
    test:
        name: "Test against content"
        runs-on: ubuntu-latest

        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: "Setup Bun"
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
              run: bun install --frozen-lockfile

            - name: "Run tests"
              run: bun run test

    build:
        name: "Build for production"
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request'
        needs: test

        steps:
            - name: "Build for production and upload"
              uses: withastro/action@v2

    deploy:
        name: "Deploy to GitHub Pages"
        runs-on: ubuntu-latest
        needs: build
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}

        steps:
            - name: "Deploy to GitHub Pages"
              id: deployment
              uses: actions/deploy-pages@v4
